[package]
name = "hello_world"
version = "0.0.1"
authors = ["Tyler Thrailkill <tyler.b.thrailkill@gmail.com>"]
workspace = "../../"

[dependencies]
CQRuSt = { path = "../../lib" }
CQRuSt_codegen = { path = "../../codegen" }
rocket = { version = "0.1.2" }
rocket_codegen = { version = "0.1.2" }

[dev-dependencies]
CQRuSt = { path = "../../lib", features = ["testing"] }
